#!/usr/bin/env bash
# Detects the host environment (native Linux vs WSL2) and writes the
# values the docker-compose stack needs to .env.detected.
#
# Outputs (sourced by the Makefile):
#   COMPOSE_OVERRIDE   path to the right docker-compose.<env>.yml
#   RENDER_GID         numeric GID of the host's render group
#   HAS_NPU            1 if /dev/accel/accel0 is exposed, 0 otherwise
#   HAS_IGPU           1 if /dev/dri/renderD* is exposed, 0 otherwise
#   IS_WSL2            1 if running under WSL2, 0 otherwise
#
# Safe to run anywhere — read-only inspection of /proc and /dev.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/.env.detected"

is_wsl2=0
if grep -qiE 'microsoft|wsl' /proc/version 2>/dev/null; then
  is_wsl2=1
fi

has_igpu=0
if compgen -G '/dev/dri/renderD*' >/dev/null; then
  has_igpu=1
fi

has_npu=0
if [ -e /dev/accel/accel0 ]; then
  has_npu=1
fi

# Render GID: WSL2 exposes a synthetic group (often 992 / no name).
# Native Linux uses the real "render" group from the host.
render_gid=""
if [ "$is_wsl2" = "1" ]; then
  # On WSL2 the render device has a synthetic GID with no matching group name.
  render_gid="$(stat -c '%g' /dev/dri/renderD128 2>/dev/null || echo 992)"
else
  render_gid="$(getent group render | cut -d: -f3 || true)"
  [ -z "$render_gid" ] && render_gid="$(stat -c '%g' /dev/dri/renderD128 2>/dev/null || echo 105)"
fi

if [ "$is_wsl2" = "1" ]; then
  override="docker-compose.wsl2.yml"
  env_label="WSL2"
else
  override="docker-compose.linux.yml"
  env_label="Linux native"
fi

cat > "$OUT" <<EOF
# Auto-generated by scripts/detect-env.sh. Do not edit by hand.
COMPOSE_OVERRIDE=$override
RENDER_GID=$render_gid
HAS_NPU=$has_npu
HAS_IGPU=$has_igpu
IS_WSL2=$is_wsl2
EOF

echo "Detected environment: $env_label"
echo "  override:    $override"
echo "  render GID:  $render_gid"
echo "  iGPU:        $([ "$has_igpu" = "1" ] && echo yes || echo no)"
echo "  NPU:         $([ "$has_npu" = "1" ] && echo yes || echo no)"
echo "  written to:  $OUT"
